spring:
  application:
    name: MomentService
  cloud:
    nacos:
      server-addr: localhost:18375
      username: nacos
      password: Xp4#tG7!vQ
      
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/InfiniteChat?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: gK3T9n%q2M@j7Z4
    hikari:
      # 设置最大连接池大小
      maximum-pool-size: 30
      # 设置最小空闲连接数
      minimum-idle: 10
      # 设置连接池初始化失败时的超时时间
      initialization-fail-timeout: 10000
      # 设置连接池的最大空闲时间
      idle-timeout: 30000
      # 设置连接池中连接的最大生命周期
      max-lifetime: 60000
      # 设置连接池的连接超时时间
      connection-timeout: 30000
      # 设置连接池的最大等待时间
      validation-timeout: 3000
      # 配置连接池验证SQL（根据数据库选择合适的SQL）
      connection-test-query: SELECT 1
      # 设置连接池的池化管理名称
      pool-name: HikariCP
  jmx:
    enabled: true
  redis:
    host: localhost
    port: 59000
    password: e65K4t8w2
server:
  tomcat:
    connection-timeout: 60000
  port: 8086
logging:
  level:
    com.shanyangcode.infinitechat.momentservice.mapper : debug


#  暴露健康检查和性能监控端点（health、metrics）
management:
  endpoints:
    web:
      exposure:
        include: health,metrics